### ISSUE TITLE
Backend (Adminpanel)

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#10]
* [ ] Übersichtskarte
  * [x] Teamübersicht / Verwaltung
  * [x] Stationen verwalten
  * [ ] Bilderstream
  * [x] Verwalten der Nachrichten (Notifications)
  * [x] Passcode/Mr.X Verwaltung
  * [x] Rätsel Verwaltung
  * [x] QR codes generieren

**Comment by demianh** [comment]
für die zwei offenen punkte gibts einzelne issues
