### ISSUE TITLE
Nur "Scanbot" als QR Code App auf Infozettel aufführen

### ISSUE THREAD

**Issue by demianh** [pio-x/pio-x#113]
Mit der anderen App geht es nicht richtig da sie es im eigenen, integrierten Browserfenster aufmacht

**Comment by e-monkey** [comment]
Hab ich im DSK Dokument aufgenommen, muss für den normalen Pio-X Anlass noch angepasst werden.

**Comment by e-monkey** [comment]
iOS kann ab version 11 mit der normalen Systemkamera ein QR-code gescannt werden
