### ISSUE TITLE
Infoseiten mit QR Codes vollständig via Backend drucken

### ISSUE THREAD

**Issue by demianh** [pio-x/pio-x#132]
Damit man nicht mehr mit Word die Vorlage machen und dann zweimal durch den Drucker lassen muss.
Ein WYSIWYG Editor für den Text auf dem Infoblatt wäre praktisch, zusammen mit einem fixen Teil der QR Code, Name, Link etc. enthält.

**Comment by e-monkey** [comment]
Grundsätzlich funktioniert es nun. Folgende Punkte sind noch offen:
-  [x] Seitentrenner  zwischen den ersten beiden Seiten entfernen. Die Trennung soll automatisch gemacht werden. Notfalls mit mehreren Zeilenumbrüchen. So kann der ganze Seiteninhalt in einer Variable gespeichert werden.
 -  [x] Titel und Inhalt soll über die API aufgerufen werden können.
 -  [x] Titel und Inhalt soll über das Backend konfiguriert werden können.

**Comment by demianh** [comment]
ist nun so umgesetzt
