### ISSUE TITLE
Server URL in QR Code einbauen, damit App unabhängiger wird

### ISSUE THREAD

**Issue by demianh** [pio-x/pio-x#135]
Damit wäre es möglich unterschiedliche Instanzen aufzusetzen ohne eine neue App zu publizieren, z.b auch ad-hoc auf einem Amazon Server

**Comment by laurenzgamper** [comment]
Ist jetzt in der Config des Backends

**Comment by laurenzgamper** [comment]
reopen

**Comment by laurenzgamper** [comment]
fixed
