### ISSUE TITLE
Backend: Stream verbessern

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#36]
Backend: Stream implementieren

**Comment by e-monkey** [comment]
Der Stream funktioniert in einer ersten Form. Allerdings muss die Bildanzeige noch überarbeitet werden.

Was man auch machen könnte: Das Design abhängig vom Typ machen.

**Comment by demianh** [comment]
TODO: 
- team id als spalte einfügen
- remove/save buttons entfernen

dann ist das gut so :)
