### ISSUE TITLE
Backend: riddles: unnötige Felder raus

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#41]
Backend: riddles: unnötige Felder raus

**Comment by e-monkey** [comment]
Der Typ ist nun ein Auswahlfeld. Die View braucht aber noch:
  * [ ] Breite der Felder anpassen
  * [ ] Optional: Locationpicker

**Comment by demianh** [comment]
Es fehlen noch die Felder "answer_required" und "image_required" im backend. Die sollte man auch bearbeiten können

**Comment by e-monkey** [comment]
im riddle tab und auf der backend map gefixt
