### ISSUE TITLE
Rover X am 5.März

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#45]
5.März: 14:00 Checking, 14:30 go, 16:30 Fertig, 17:00 Ade messi

Folgende Punkte haben wir heute als bis am Sonntag zu erledigen definiert:
  * [x] Wo Checkin? (Laptop, Tisch, bank überdacht?)
  * [x] Rätsel erfassen
  * [x] Mehr Stationen erfassen
  * [ ] Belohnung organisieren
  * [x] Subdomains auf Cyon löschen
  * [x] DNS umstellen
  * [x] Whatsapp Werbung
  * [x] 1-2 Mr.X finden
  * [x] Dummy Teams erstellen
  * [ ] Teamblätter drucken
  * [x] Passcodes generieren
  * [ ] Passcodes drucken
  * [x] Infotext in App anpassen

**Comment by e-monkey** [comment]
Folgende Punkte haben wir heute als bis am Sonntag zu erledigen definiert:
  * [ ] Subdomains auf Cyon lösche
  * [ ] Pio-X auf DigitalOcean installieren
  * [ ] DNS umstellen
  * [ ] Stationen mit Punkten erfassen (Backend)
  * [ ] Stationen auf Backend Map editieren

**Comment by demianh** [comment]
ist ja schon vorbei ;)
