### ISSUE TITLE
iPhone 5s testen

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#50]
Wir haben es Gestern auf einem iPhone 5s nicht zum laufen gekriegt. Eventuell wird das schlimmer je mehr Stationen wir erfassen, da wir den Mobilebrowsern von nicht mehr ganz aktuellen System überlasten?

Ich werde dieses Wochenende so viele Stationen wie möglich erfassen, damit wir das auch mit anderen Geräten noch etwas durchtesten können.

**Comment by e-monkey** [comment]
Auf dem Wiko LENNY2 mit Android 5.1 und 768MB RAM im Chrome funktionert es. (sehr ruckelig)

**Comment by demianh** [comment]
iPhone Bug ist gefixt
