### ISSUE TITLE
Klick Problem auf Map (Map Infos)

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#54]
Wenn eine Station nahe an einem Infopoint von Google ist, öffnet sich der Googleinfopoint und man kann die Infos bzw. den Tooltip der Station nicht mehr öffnen.

**Comment by demianh** [comment]
Kann via "clickableIcons" disabled werden, die google map implementation kann dass aber nicht...
https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions

**Comment by e-monkey** [comment]
Wenn man genug weit wegzoomt, verschwindet das GoogleIcon und man kann die Station einnehmen. Manchmal muss man aber die Karte neu laden. Eventuell können wir eine Tech-FAQ machen, wo das drin steht.

Gibt es bei der Karte die wir nutzen einen Feature Request dazu?

**Comment by demianh** [comment]
hab ein pull request aufgemacht.. bei einem feature request hast du keine chance dass der so schnell gemacht wird...

https://github.com/SebastianM/angular2-google-maps/pull/923
