### ISSUE TITLE
Infoblatt für Teams

### ISSUE THREAD

**Issue by ewangler** [pio-x/pio-x#69]
Auf Infoblatt
- klarer ablauf
- akku verbrauch limitieren
- regeln fuer foto -> dass das team drauf sein muss etc.
- wie station einnehmen

vorab infos
- chrome installieren,...
- gruppenname

**Comment by e-monkey** [comment]
Info zu ÖV Ticket soll auch rein

**Comment by e-monkey** [comment]
Erster Entwurf siehe https://github.com/pio-x/pio-x/commit/3a56c20f261e717f63746661865c20256e45134b

**Comment by e-monkey** [comment]
Ist im Infodokument und auf der Infoseite in der App
