### ISSUE TITLE
Moderation Fotorätsel

### ISSUE THREAD

**Issue by demianh** [pio-x/pio-x#82]

**Comment by e-monkey** [comment]
Ist es hier gedacht, dass wir den normalen Stream "filtern" oder wollen wir dazu einen eigenen Endpoint in der API? @demianh

**Comment by demianh** [comment]
mein vorschlag wäre alle rätsel aufzulisten mit allen fotos mit denen es gelöst wurde...

**Comment by demianh** [comment]
- Akkordion mit Liste der Rätseln
- Alle Bilder pro Rätsel auflisten mit Team Name, Team ID

**Comment by laurenzgamper** [comment]
Gibt jetzt ein Interface für die gelösten Rätsel
